[prompt]
about_user = "I am a curious human programmer."
response_preference = "Basic concepts don't need to be explained."
files = []

[prompt.project]
activitywatch = "ActivityWatch is a free and open-source automated time-tracker that helps you track how you spend your time on your devices."
gptme = "gptme is a CLI to interact with large language models in a Chat-style interface, enabling the assistant to execute commands and code on the local machine, letting them assist in all kinds of development and terminal-based work."

[env]
GEMINI_API_KEY = "AIzaSyDkfe2f5DpGaw-jicAvfERJ1J8Ou-SQUos"

MODEL = "gemini/gemini-2.5-flash"
